name = "Nook and Cranny"
license = "Copyright &copy; 2017 - The Nook and Cranny Digest - All Rights Reserved"
licenselink = ""
description = "Nook and Cranny is a theme designed for The Nook and Cranny Digest by @jeffreyhyer"
homepage = "https://github.com/jeffreyhyer/hugo-nook-and-cranny"
tags = ["blog", "minimal", "elegant", "white", "nook", "cranny", "hugo"]
features = ["blog", "disqus", "google analytics", "pagination", "rss", "sharing options"]
min_version = 0.18

[author]
    name = "Jeffrey Hyer"
    homepage = "https://github.com/jeffreyhyer"
