#!/bin/bash

folders=$(ls)

for folder in $folders
do
    i=1
    files=$(ls $folder/ | grep "png")

    for filename in $files
    do
        convert "$folder/$filename" "$folder/$i.jpg"
        composite -gravity southeast -geometry 100%x100%+25+12 "/Users/jeffreyhyer/Dropbox/The Nook & Cranny Digest/Image Watermark.png" "$folder/$i.jpg" "$folder/$i.jpg"
        rm "$folder/$filename"
        ((i++))
    done
done
